### ISSUE TITLE
Add a python requirements.txt

### ISSUE THREAD

**Issue by dennislwm** [MiguelMJ/Answerable#1]
Using Python 3.7.9

Expected behaviour: Save the user
$ python answerable.py save -u <ID>

Current behaviour:
Traceback (most recent call last):
  File "answerable.py", line 7, in <module>
    from tools import fetcher, displayer, recommender, log
  File "D:\Users\denni\OneDrive\Documents\GitHub\Answerable\tools\fetcher.py", line 12, in <module>
    from bs4 import BeautifulSoup
**ModuleNotFoundError: No module named 'bs4'**

Relevant information:
Please provide a python requirements.txt file for modules that are required.

**Comment by MiguelMJ** [comment]
I have generated the requirements.txt using pipreqs, I think that should do it. Thanks for addressing it, don't hesitate to do it again if you have any problem ;)

**Comment by MiguelMJ** [comment]
@all-contributors please add @dennislwm for bug
